apiVersion: v1

kind: Pod

metadata:
    name: test-pod

    # annotations can have any key and value strings
    annotations:
        description: Demo for Exposing ports inside a container

spec:
    containers:
        - name: c01
          image: httpd:2.4
          ports:
              - containerPort: 80
    restartPolicy: Never
