apiVersion: v1

kind: Pod

metadata:
    name: test-pod

    # annotations can have any key and value strings
    annotations:
        description: Create POD with resources, having requests and limits

spec:
    containers:
        - name: c01
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello-Lokesh; sleep 5; done"]
          resources:
              requests:
                  memory: "64Mi"
                  cpu: "100m"
              limits:
                  memory: "128Mi"
                  cpu: "200m"




# kubectl apply -f 100_pod_with_resources.yml
# 
# kubectl get pods -o wide
#
#      NAME       READY   STATUS    RESTARTS   AGE   IP           NODE             NOMINATED NODE   READINESS GATES
#      test-pod   1/1     Running   0          6s    10.1.0.105   docker-desktop   <none>           <none>
