apiVersion: v1

kind: ResourceQuota

metadata:
    name: test-resource-quota
#    namespace: test-namespace

spec:
    hard:
        limits.cpu: "400m"                  
        limits.memory: "400Mi"
        requests.cpu: "200m"
        requests.memory: "200Mi"
        pods: "20"                      # Max 20 pods in this namespace
