apiVersion: v1

kind: Pod

metadata:
    name: test-pod

    # annotations can have any key and value strings
    annotations:
        description: Demo for LimitRange

spec:
    containers:
        - name: c01
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo 'I am container c01'; sleep 5; done"]

          resources:
              limits:
                  cpu: "1400m"
              requests:
                  cpu: "200m"



# kubectl apply -f 116_pod_outside_limit.yml
# 
# 
# kubectl get limitrange
# 
#     NAME               CREATED AT
#     test-limitrange   2026-01-30T00:54:45Z
# 
# 
# kubectl describe limitrange test-limitrange
# 
#     Name:                  test-limitrange
#     Namespace:             default
# 
#     Type                   Resource  Min    Max   Default Request  Default Limit  Max Limit/Request Ratio
#     ----                   --------  ---    ---   ---------------  -------------  -----------------------
#     Container              cpu       100m   1     500m             500m           -
#     Container              memory    500Mi  1Gi   500Mi            500Mi          -
# 
# 
# 
# kubectl apply -f 111_pod_within_limit.yml
# 
#     O/P:
#     Error from server (Forbidden): error when creating ".112_pod_outside_limit.yml": pods "test-pod" is forbidden: maximum cpu usage per Container is 1, but limit is 1400m
# 
# # Cleanup after the testing
# 
# kubectl delete limitrange test-limitrange
