apiVersion: v1

kind: Pod

metadata:
    name: test-pod

spec:
    containers:
        - name: c01
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo 'I am container c01'; sleep 5; done"]
        - name: c02
          image: httpd
          ports:
              - containerPort: 80

# kubectl apply -f .\40_networking_containers_within_same_pod.yml
# kubectl get pods -o wide --show-labels
# kubectl describe pod test-pod
# kubectl exec test-pod -it -c c01 -- /bin/bash     --> connect with terminal of container c01
# apt update && apt install curl                    --> install curl in container c01
# curl localhost:80                                 --> call to apache, which is installed in container c02
