apiVersion: v1

kind: Pod

metadata:
    name: test-pod1

spec:
    containers:
        - name: c01
          image: nginx
          ports:
              - containerPort: 80

---

apiVersion: v1

kind: Pod

metadata:
    name: test-pod2

spec:
    containers:
        - name: c02
          image: httpd
          ports:
              - containerPort: 80


# kubectl apply -f .\41_networking_two_containers_in_separate_pod.yml
# kubectl get pods -o wide --show-labels
# curl IPOfTestPod1:80                                 --> call to nginx, which is installed in container c01
# curl IPOfTestPod2:80                                 --> call to apache, which is installed in container c02
