apiVersion: v1

kind: Pod

metadata:
    name: test-pod

    # annotations can have any key and value strings
    annotations:
        description: Demo for mounting emptyDir volume inside a POD having 2 containers

spec:
    containers:
        - name: c01
          image: ubuntu
          command: ["/bin/bash", "-c", "sleep 5000"]
          volumeMounts:
              - name: my-volume
                mountPath: "/tmp/ubuntu_data"
        - name: c02
          image: centos:centos7.9.2009
          command: ["/bin/bash", "-c", "sleep 5000"]
          volumeMounts:
              - name: my-volume
                mountPath: "/tmp/centos_data"

    volumes:
        - name: my-volume
          emptyDir: {}

# kubectl apply -f 50_volume_emptyDir_type.yml
#
#   NAME       READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
#   test-pod   2/2     Running   0          45s   192.168.0.7   controlplane   <none>           <none>
#
# kubectl exec test-pod -it -c c01 -- /bin/bash
#
# root@test-pod:/#                  cd /tmp/ubuntu_data
#
# root@test-pod:/tmp/ubuntu_data#   ll                            O/P: It does not contain any file
# 
# root@test-pod:/tmp/ubuntu_data#   echo "Hello from Ubuntu" > hello_ubuntu.txt
#
# root@test-pod:/tmp/ubuntu_data#   ll                            O/P: hello_ubuntu.txt
#
# root@test-pod:/tmp/ubuntu_data#   cat hello_ubuntu.txt          O/P: Hello from Ubuntu
#
# root@test-pod:/tmp/ubuntu_data#   exit
#
# 
# kubectl exec test-pod -it -c c02 -- /bin/bash
#
# root@test-pod:/#                  cd /tmp/centos_data
#
# root@test-pod:/tmp/centos_data#   ll                            O/P: hello_ubuntu.txt
# 
# root@test-pod:/tmp/centos_data#   cat hello_ubuntu.txt          O/P: Hello from Ubuntu
#
# root@test-pod:/tmp/centos_data#   echo "Hello from Centos" > hello_centos.txt
#
# root@test-pod:/tmp/centos_data#   ll                            O/P: hello_ubuntu.txt   hello_centos.txt
#
# root@test-pod:/tmp/centos_data#   cat hello_centos.txt          O/P: Hello from Centos
#
# root@test-pod:/tmp/centos_data#   exit
#
#
# kubectl exec test-pod -it -c c01 -- /bin/bash
#
# root@test-pod:/#                  cd /tmp/ubuntu_data
#
# root@test-pod:/tmp/ubuntu_data#   ll                            O/P: hello_ubuntu.txt   hello_centos.txt
#
# root@test-pod:/tmp/ubuntu_data#   cat hello_ubuntu.txt          O/P: Hello from Ubuntu
#
# root@test-pod:/tmp/ubuntu_data#   cat hello_centos.txt          O/P: Hello from Centos
#
# root@test-pod:/tmp/ubuntu_data#   exit
