apiVersion: v1

kind: Pod

metadata:
    name: test-pod

    # annotations can have any key and value strings
    annotations:
        description: Demo for mounting hostPath volume (from host) with a POD having 2 containers

spec:
    containers:
        - name: c01
          image: ubuntu
          command: ["/bin/bash", "-c", "sleep 5000"]
          volumeMounts:
              - name: my-volume
                mountPath: "/tmp/ubuntu_data"
        - name: c02
          image: centos:centos7.9.2009
          command: ["/bin/bash", "-c", "sleep 5000"]
          volumeMounts:
              - name: my-volume
                mountPath: "/tmp/centos_data"

    volumes:
        - name: my-volume
          hostPath:
              path: /tmp/host_data

# kubectl apply -f 51_volume_hostPath_type.yml
#
#   NAME       READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
#   test-pod   2/2     Running   0          45s   192.168.0.7   controlplane   <none>           <none>
# 
# 
# 
# Now Directory /tmp/host_data will exist in host machine, however it is empty
# 
# ll /tmp/host_data                                                     O/P: It does not contain any file
# 
# 
# 
# echo "Hello from host machine" > /tmp/host_data/hello_host.txt        --> It will create hello_host.txt at host machine's /tmp/host_data location
# 
# cat /tmp/host_data/hello_host.txt                                     O/P: Hello from host machine
# 
# 
# 
# kubectl exec test-pod -c c01 -- ls /tmp/ubuntu_data                   O/P: hello_host.txt
# 
# kubectl exec test-pod -c c01 -- cat /tmp/ubuntu_data/hello_host.txt   O/P: Hello from host machine
# 
# kubectl exec test-pod -c c01 -- echo "Hello from Ubuntu" > hello_ubuntu.txt
# 
# kubectl exec test-pod -c c01 -- ls /tmp/ubuntu_data                   O/P: hello_host.txt  hello_ubuntu.txt
# 
# kubectl exec test-pod -c c01 -- cat /tmp/ubuntu_data/hello_ubuntu.txt O/P: Hello from Ubuntu
# 
# 
# 
# ll /tmp/host_data                                                     O/P: hello_host.txt  hello_ubuntu.txt
# 
# cat /tmp/host_data/hello_host.txt                                     O/P: Hello from host machine
# 
# cat /tmp/host_data/hello_ubuntu.txt                                   O/P: Hello from Ubuntu
