apiVersion: v1

kind: Pod

metadata:
    name: test-pod

    # annotations can have any key and value strings
    annotations:
        description: Demo for reading secret as volume inside a POD

spec:
    containers:
        - name: c01
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo 'I am container c01'; sleep 5; done"]
          volumeMounts:
              - name: my-secret-volume
                mountPath: "/tmp/ubuntu_secret_data"    # the config files will be mounted as ReadOnly by default here

    volumes:
        - name: my-secret-volume
          secret:
              secretName: test-secret                   # this should match with secret name given in first command



# kubectl create secret generic test-secret --from-file=80_test_db_secret.txt --from-file=81_test_webservice_secret.txt
# 
# kubectl get secret
# 
#     NAME          TYPE     DATA   AGE
#     test-secret   Opaque   2      23s
# 
# kubectl describe secret test-secret
# 
#     Name:         test-secret
#     Namespace:    default
#     Labels:       <none>
#     Annotations:  <none>
#     
#     Type:  Opaque
#     
#     Data
#     ====
#     80_test_db_secret.txt:          32 bytes
#     81_test_webservice_secret.txt:  32 bytes
# 
# 
# 
# kubectl apply -f 82_secret_as_volume.yml
# 
# kubectl get pods -o wide
# 
#     NAME       READY   STATUS    RESTARTS   AGE   IP          NODE             NOMINATED NODE   READINESS GATES
#     test-pod   1/1     Running   0          7s    10.1.0.97   docker-desktop   <none>           <none>
# 
# 
# kubectl exec test-pod -c c01 -it -- /bin/bash     # Both the commands are same, since there is only 1 container in the pod test-pod
# kubectl exec test-pod -it -- /bin/bash            # Both the commands are same, since there is only 1 container in the pod test-pod
# 
# root@test-pod:/# ll /tmp/ubuntu_secret_data       --> app1.conf
# 
# root@test-pod:/# cat /tmp/ubuntu_secret_data/80_test_db_secret.txt
# 
#     dbkey1=dbvalue1
#     dbkey2=dbvalue2
# 
# root@test-pod:/# cat /tmp/ubuntu_secret_data/81_test_webservice_secret.txt
# 
#     wskey1=wsvalue1
#     wskey2=wsvalue2
# 
# 
# 
# # Cleanup after the testing
# 
# root@test-pod:/# exit
# 
# kubectl delete secret test-secret
# 
# kubectl delete -f 82_secret_as_volume.yml
